### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by turkeyroastbig** [BSData/black-powder#1]
Hi, I'm Turkeyroastbig,
I'd like to contribute to this repository, because it is still in it's default state, and I want to get it up and running for Black Powder. I have already started cataloguing data from some of Black Powders Books and would be willing to at least get the Peninsular War books data into Battlescribe. 

CC: @BSData/owners

**Comment by amis92** [comment]
/invite

---
[Workflow run](https://github.com/BSData/chatops/actions/runs/1196903310)
:robot: Invited @turkeyroastbig with **push** access. Invite can be accepted on https://github.com/BSData/black-powder/invitations
